### ISSUE TITLE
Wrong method call

### ISSUE THREAD

**Issue by plus-** [tinode/tindroid#100]
I was browsing the sources when I noticed you're passing the wrong arguments to the localized title for notifications:

https://github.com/tinode/tindroid/blob/1add27e45d3ab16bff4a2eb6f74d08c669f6634b/app/src/main/java/co/tinode/tindroid/services/FBaseMessagingService.java#L331-L332

it should be [getTitleLocalizationArgs](https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/RemoteMessage.Notification#getTitleLocalizationArgs()) instead of  `getBodyLocalizationArgs`

**Comment by or-else** [comment]
Thanks, fixed: https://github.com/tinode/tindroid/commit/b3f9aaaccaca7a1eb32a824c75fcdd78be7d1382
