### ISSUE TITLE
FAILURE: Build failed with an exception. 

### ISSUE THREAD

**Issue by reBiocoder** [tinode/tindroid#101]
**Describe the bug**
build fail
ERROR: For input string: ""

**Screenshots**
![截屏2021-02-11 上午12 00 25](https://user-images.githubusercontent.com/39401819/107535919-27e23980-6bfc-11eb-8832-ca7ab41df3a7.png)

git is correct.
![截屏2021-02-11 上午12 02 03](https://user-images.githubusercontent.com/39401819/107536111-60821300-6bfc-11eb-966b-afaf6e97c5be.png)

What happened? thank you very much

**Comment by or-else** [comment]
It looks like the `"git rev-list --count HEAD".execute()` returns `""` in your case. Your "git is correct" is executed in `master/` while your code is being built in `tindroid-0.16.9/`.

**Comment by reBiocoder** [comment]
> It looks like the `"git rev-list --count HEAD".execute()` returns `""` in your case. Your "git is correct" is executed in `master/` while your code is being built in `tindroid-0.16.9/`.

thanks!

**Comment by srvkumar52** [comment]
i have same problem how to solve this problem lease guide me
