### ISSUE TITLE
Image files become unavailable when using file transfer button

### ISSUE THREAD

**Issue by young310** [tinode/tindroid#106]
**Describe the bug**
When the user transfer image format files, if the user choose file button, the uploaded file will become unavailable.
But if the user use the image button, everything seems ok.

**To Reproduce**
1. Press file button
2. Select image file, such as JPG, PNG
3. Press send button
4. See error, file unavailable

**Expected behavior**
The image file should upload normally, and will show the preview thumbnail

**Screenshots**
![IMG_20210510_151027](https://user-images.githubusercontent.com/8056293/117619669-21833f80-b1a2-11eb-9eaa-6679bc68b5f7.jpg)

**Tindroid (please complete the following information):**
 - Version 0.17
 - Device Poco F3
 - Android API Version 29

**Server**
- Type my own setup
- Server type unmodified
- Server version 0.16.10

**Additional context**
There is no error msg on server-side nor client-side

I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=63175d63-456b-4b8e-8605-d16370611b88, tags={ AttachmentUploader, co.tinode.tindroid.AttachmentHandler } ]
D/Tinode: out: {"pub":{"content":{"ent":[{"data":{"val":"/9j/4QrhRXhpZgAATU0AKgAAAAgABwESAAMAAAABAAEAAAEaAAUAAAABAAAAYgEbAAUAAAABAAAAagEoAAMAAAABAAIAAAExAAIAAAAhAAAAcgEyAAIAAAAUAAAAk4dpAAQAAAABAAAAqAAAANQALcbAAAAnEAAtxsAAACcQQWRvYmUgUGhvdG9zaG9wIDIxLjIgKE1hY2ludG9zaCkAMjAyMTowNToxMCAxNDoyMzoyMgAAAAOgAQADAAAAAQABAACgAgAEAAAAAQAABACgAwAEAAAAAQAABAAAAAAAAAAABgEDAAMAAAABAAYAAAEaAAUAAAABAAABIgEbAAUAAAABAAABKgEoAAMAAAABAAIAAAIBAAQAAAABAAABMgICAAQAAAABAAAJpwAAAAAAAABIAAAAAQAAAEgAAAAB/9j/7QAMQWRvYmVfQ00AAf/uAA5BZG9iZQBkgAAAAAH/2wCEAAwICAgJCAwJCQwRCwoLERUPDAwPFRgTExUTExgRDAwMDAwMEQwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwBDQsLDQ4NEA4OEBQODg4UFA4ODg4UEQwMDAwMEREMDAwMDAwRDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDP/AABEIAKAAoAMBIgACEQEDEQH/3QAEAAr/xAE/AAABBQEBAQEBAQAAAAAAAAADAAECBAUGBwgJCgsBAAEFAQEBAQEBAAAAAAAAAAEAAgMEBQYHCAkKCxAAAQQBAwIEAgUHBggFAwwzAQACEQMEIRIxBUFRYRMicYEyBhSRobFCIyQVUsFiMzRygtFDByWSU/Dh8WNzNRaisoMmRJNUZEXCo3Q2F9JV4mXys4TD03Xj80YnlKSFtJXE1OT0pbXF1eX1VmZ2hpamtsbW5vY3R1dnd4eXp7fH1+f3EQACAgECBAQDBAUGBwcGBTUBAAIRAyExEgRBUWFxIhMFMoGRFKGxQiPBUtHwMyRi4XKCkkNTFWNzNPElBhaisoMHJjXC0kSTVKMXZEVVNnRl4vKzhMPTdePzRpSkhbSVxNTk9KW1xdXl9VZmdoaWprbG1ub2JzdHV2d3h5ent8f/2gAMAwEAAhEDEQA/APVUkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklP/9D1VJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJT//R9VSSSSUpJJJJTQ6zl34uK2yhwa42BpJE6Q4/99VrFsdZi02P1c+trnHjUgErP+sX9CZ/xo/6l6vYP9Cx/wDimf8AUhDquPyjzczMz+pftKzExS0xGxhA/cD3e5xCRt+sjBuNbXAcgBh/Btm5MP8AxTH/AF/wS20kk1Wg2c3p3WBlWfZ72elfrETBI+k2He5j2/uLSWD1Zor6vjWVj3uNZcB3IfsH+c32K71zMdjYm1h2vuO2RyGgTY4f2fakgiyK6o8zrRFv2bBZ690kF0EtkchrW/zm38/8xDFf1ksG42Nr/k+z/vrLf+rVrpOAzExmuLf09gBsPh+7UP5LFfSUSBoAPq4bsrr2IQ+9gtrn3GARHxp2uZ/brW4kkigm+lKSSSSQpJJJJSkkkklP/9L1VJJJJSkkkklOV9Yv6Ez/AI0f9S9XsH+hY/8AxTP+pCz/AKyWNbiVM/ONm6PJrXT/ANU1aWKw14tNbuWMa0/EABDquPyjzcPKyWYvXn5FgJYyJDYnWtrfzi1WX/WXGj9HU9zuwcWgf9F1n/UocA/WUgiR4f8AWgtoMY0y1oB8QEkkjSxegcfAxMvLzB1DNbsa3WthESR9CGH3Nrr+l7vpvUfrH/PYwP0YdP317luLK+sOMbcVtzRPok7v6jhD3f2fY5LooSuQdVVOo5WVjVsdjUm9znQ4AOMCCd3sBS6bmty8Vrp/SsAba3uHDv8A1X/SaraK3Y6uFd1zqNLd1uKK+Y3h7ZIE/nBbjTLQfESsb6zf0en+s7/qStiv+bb8AgmVUCBTJJJJFapJJJJSkkkklP8A/9P1VJJJJSlR6jb1Go1Owqxa33CxpAP7uz8+t376vJJJBpxKun5+dlNyOowytnFemsHdsDWl21m7+c3O9RbaSSSibcoYWV+3Dl7P0H78j/R7Po/S+mtVJJJRN14aKTEAggiQdCCnSSQ4t/RsnHt9fptmw/6MmCB+61xlj2f8HakMr6wt9hx2uP7xA/77cGLaSQpdxdwC4VnTur9QI+2PbUwTA0MT+6yv/v8Aatxo2tA8BCdJFBNqSSSSQpJJJJSkkkklP//U9VSSSSUpJJVOov6gxjDgsD3l3vBj6MH959f5yShq20liWZf1grY6yyljWMBc50AwBqTpco0Z/XchnqUVseySJAA1H9a1qFruE9w7qSz+n29Wfc4ZtbWVbZaRH0pH7tln5qr53UeoV9Q+yYoY6Q3Y0jUkgud7t7G/moo4da0dhJY3r/WP/QM+5v8A6WVvp1nU3us+3VtraA304jU+7f8ARfZ/JSUY11DeSVLqXU68FgEb7n/QZMaD895/NaqQf9Y7xvaG0tOoaQ0f9Gz1H/5yVqETvt5u0ksnDyOsszK6cxk1WSC/aDENc4e+o7W/R/PajdQt6sy5owq2vq2y4mPpSf3rK/zUlcOtWHQSWFfn9dx2epfWxjJAkgHU/wBW1ylXl/WCxjbK6WOY8BzXQBIOoOtyFp4T3DtpKp05/UHsec5gY8O9gEfRgfuvs/OVtFadFJJJJKf/1fVUkkklKSSSSU1upf8AJ+T/AMU//qSq3QP6Af8AjHKz1L/k/J/4p/8A1JVboH9AP/GOQ6rv0T5uksS//wAUdX9n/qLFtrn+o+v+2x9mj19rfTmIna/972/RSKobnyegSWLP1l8G/wDgav8ATvt/ou+3R6m/2xH0Yb+5/K3IoIrqHM6i9tPXKrb/AOaAY4E8ADcJ/wCt2e9boIIBBkHUEKvm4NGbWGWyHN1ZYPpNPl/5FZJr6t0iTWfWxh2AJaB51/zlP9j9Egu0kB3DvpKl0/qlGcIb7LQJdWTOn7zHfnsV1FYRW7m9f/oA/wCMarPTf+T8b/imf9SFW6//AEAf8Y1Wem/8n43/ABTP+pCHVd+iPNspJJIrVJJJJKf/1vVUkkklKSSSSU1upf8AJ+T/AMU//qSq3QP6Af8AjHK3nVvtw766xue+tzWjQSSIHKB0fHvx8Q13s2P3uMSDof6pcl1Xfo/VvLEv/wDFHV/Z/wCosW2sXPxOonqf2vFq3bWt2OJbEw5rva5zf3kCqO58naSWN6v1l/0TP+h/6VVnp7+ruvIzmNbVsMEbfpS2Povf+buRQY+IdBJZObR1evMfkYR3VvAmuRyBGtdkN/zHIYz+vH2jEG7x2kD8bNv/AEkrTw+IRdTqZidUotxwGueWuLG6a7tjv+3muW+sjD6Zl25Qzeoul7YLKwQdR9Ddt9jWs/NYxa6AVI7DenN6/wD0Af8AGNVnpv8Ayfjf8Uz/AKkIXWMe/IxBXQze/e0xIGg/rFqPg1vqw6K7BteytrXDQwQIPCPVX6P1TpJJJLVJJJJKf//X9VSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSU//0PVUkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklKSSSSUpJJJJSkkkklP/9n/7RMOUGhvdG9zaG9wIDMuMAA4QklNBCUAAAAAABAAAAAAAAAAAAAAAAAAAAAAOEJJTQQ6AAAAAAEfAAAAEAAAAAEAAAAAAAtwcmludE91dHB1dAAAAAUAAAAAUHN0U2Jvb2wBAAAAAEludGVlbnVtAAAAAEludGUAAAAAQ2xybQAAAA9wcmludFNpeHRlZW5CaXRib29sAAAAAAtwcmludGVyTmFtZVRFWFQAAAAeADYARgBfAEIAcgBvAHQAaABlAHIAIABNAEYAQwAtAEwAMgA3ADQAMABEAFcA
D/Tinode: in: {"ctrl":{"id":"114054","topic":"usr9I7MaS84QPE","params":{"seq":14},"code":202,"text":"accepted","ts":"2021-05-10T07:24:42.055Z"}}

**Comment by or-else** [comment]
I cannot reproduce. I guess something is not setup properly.

<img width="376" alt="Screenshot 2021-05-10 at 10 12 05" src="https://user-images.githubusercontent.com/5938143/117698287-3f659a00-b1cc-11eb-949b-2c334b6164db.png">

**Comment by young310** [comment]
> I cannot reproduce. I guess something is not setup properly in your installation. Or attach the file you are sending. Maybe it's specific to that file.
> 
> <img alt="Screenshot 2021-05-10 at 10 12 05" width="376" src="https://user-images.githubusercontent.com/5938143/117698287-3f659a00-b1cc-11eb-949b-2c334b6164db.png">

1. I tried web.tinode.co server had the same result, so I think this is not relevant to server setting.
2. I tried the same two files with picture upload button and file upload button. The picture button works will but not file upload button. Please refer to the snapshots. Any idea?
![Screenshot_2021-05-12-01-16-30-169](https://user-images.githubusercontent.com/8056293/117857959-f3941d00-b2bf-11eb-81bb-d5cbbefd749d.jpg)

**Comment by or-else** [comment]
> I tried web.tinode.co server had the same result, so I think this is not relevant to server setting.

You already asked this. I already answered: The web.tinode.co is behind nginx. Our nginx is configured to reject very large files. Please do not use web.tinode.co for testing. Please let me know if there is any further confusion with respect to web.tinode.co.

**Comment by young310** [comment]
> > I tried web.tinode.co server had the same result, so I think this is not relevant to server setting.
> 
> You already asked this. I already answered: The web.tinode.co is behind nginx. Our nginx is configured to reject very large files. Please do not use web.tinode.co for testing. Please let me know if there is any further confusion with respect to web.tinode.co.

1. This two files are **quite small**, 12kb and 62kb. I tried sandbox server and the upload process will just stop but not likely the web.tinode.co one does. 
2. With my own server setting, I tried large size files, i.e. pptx and pdf works fine. But only the image file with file upload button will fail and respond "unavailable message". But you can upload these two files with the "image button", which means it not relevant to the specific files.

**Comment by young310** [comment]
problem solved by upgrading okhttp to new version.
