### ISSUE TITLE
Not adding new contacts in ChatsFragment

### ISSUE THREAD

**Issue by MajideND** [tinode/tindroid#109]
If a user remains online in the chats list and gets a message from a user who didn't send a message before, a message will not add to ChatsAdapter most of the time.
I checked, and the server has sent new sub information with WebSocket, but the android version of the project didn't work.

How to test?
Create two users, get them online and send from one of them to another for the first time when the second is online.

**Comment by or-else** [comment]
I cannot reproduce. Could you please send me step by step instructions how to reproduce the issue reliably or send client-side logs.
