### ISSUE TITLE
Registration : Can't signup in the application

### ISSUE THREAD

**Issue by ektapatel22** [tinode/tindroid#115]
**If you are not reporting a bug, please post to https://groups.google.com/d/forum/tinode instead.**
---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Tindroid (please complete the following information):**
 - Version [e.g. 0.16.0-rc2]
 - Device [e.g. Stock Emulator or Pixel 2]
 - Android API Version [e.g. 28]

**Server**
- Type [e.g. api.tinode.co or your own setup]
- Server type [unmodified or customized]
- Server version [e.g. 0.16.0]

**Additional context**
Attach server-side and client-side logs (logcat).

**Comment by or-else** [comment]
No valid description.
