### ISSUE TITLE
No submit button on signup screen

### ISSUE THREAD

**Issue by blasius** [tinode/tindroid#124]
**Bug description**
When I want to signup, I can't find the submit button. All the fields are there but I can't find a UI component to send the information

**To Reproduce**
1. Launch the app
2. Click the signup icon in up/right corner
3. Scroll down the signup screen/page
4. Can't see a send/signup button

**Expected behavior**
When scrolling, I should see a button or UI component for validating/sending filled form to server 

**Screenshots**

**Tindroid (please complete the following information):**
 - Version [0.19.2 (Currently on Google Play]
 - Device [AP02]
 - Android API Version [8.1.0]

**Server**
- Type [Official server]
- Server type [Official]
- Server version [Current official]

**Additional context**
If of any help, my device is the size of an iPhone 7 but I can't figure out the exact dimensions of the screen

**Comment by or-else** [comment]
![Screenshot_20220715-085456](https://user-images.githubusercontent.com/5938143/179260888-71192894-1903-47d1-8452-acd26f98a262.png)

**Comment by blasius** [comment]
Shall I record my screen?

**Comment by or-else** [comment]
Sure, please demonstrate the bug so I can reproduce the problem.

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tindroid/pull/125
