### ISSUE TITLE
Login often fails after "Create new user"

### ISSUE THREAD

**Issue by etcinitd** [tinode/tindroid#13]
1. Tap on “Create new user” button 
1. Fill all fields
1. Tap on “Sign Up”
1. Try to login with the new username and password

Sometimes a user can login, but most often I get the following error:

"Login failed: already authenticated (409)"

**Comment by or-else** [comment]
Looking into it now.

**Comment by or-else** [comment]
I almost finished it but had to make some server-side changes. I'll push update tomorrow morning.

**Comment by or-else** [comment]
Fixed: https://github.com/tinode/android-example/commit/2bd2dd51954b53b029fcbdec1b7962b8769dcb48

It requires the devel server. I'll build docker containers tomorrow morning.

**Comment by or-else** [comment]
Docker released, server at api.tinode.co updated.
