### ISSUE TITLE
Images in "Image Preview" appear only once if S3 is used

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/tindroid#134]
**Description**

Images in "Image Preview" appear only once. This bug occurs only when images are hosted on S3 (I didn't test it with FS). There are no problems with images that are stored in the database. It should not be a S3 configuration problem because it's possible to upload and download files, images. The problem is only with "Image Preview".

The problem appears both on the emulator and on the phone

**To Reproduce**

Put `"use_handler": "s3"` in tinode.conf.file

Tap on the image in a received message:

![p3](https://user-images.githubusercontent.com/54183931/203270998-6c2d6549-72af-45d0-80d1-3112e67530d8.jpg)

Will open Image Preview and in ~1 second will appear the image.

![p1](https://user-images.githubusercontent.com/54183931/203271465-67c8cb83-1b05-402d-8165-270a085a7cf1.jpeg)

Now go back to the topic and tap on the same image one more time. The image will not appear:

![p2](https://user-images.githubusercontent.com/54183931/203271648-ee55c3d0-e458-47ce-b07f-5bc27d9fc50a.jpeg)

**Emulator log**

D/EGL_emulation: app_time_stats: avg=326.47ms min=3.71ms max=5436.29ms count=17
E/ImageViewFragment: Image loaded before ImageView is ready

**Tindroid**
 - Version: v0.20.8
 - Emulator: Pixel_3a_API_33_x86_64

**Telephone**
- Samsung
- Android version: 11

**Server**
- Tinode server version: 0.20.1
- Database: MySQL
- Server type: unmodified

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tindroid/commit/f830ac57218645ba2a6d6cc16de77d46fc271dbb
Please verify. Thanks.

**Comment by sanmiguel2019** [comment]
Yes, it's fixed now and images appear. Thank you.
