### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by piratov** [tinode/tindroid#135]
Please change the translation. **ПО АДРЕСУ** -> **ПО ID**
![Screenshot_16](https://user-images.githubusercontent.com/17856390/204137979-462eef2a-3f0f-4307-8d26-b3757013a461.png)

like web
![Screenshot_15](https://user-images.githubusercontent.com/17856390/204138061-611623f3-a44a-44ab-a07e-f5680374130b.png)

**Comment by or-else** [comment]
Fixed in https://github.com/tinode/tindroid/commit/a8123c2e4ab4b3e09cbfb9caf3970b4a6df8ab30. Thanks.
