### ISSUE TITLE
Crash when trying to see Bob’s profile

### ISSUE THREAD

**Issue by etcinitd** [tinode/tindroid#14]
1. Sign into Carol’s account
2. Open Bob’s profile
3. App crashes

Surprisingly, it doesn’t crash if you open Bob’s profile from Alice’s account.

**Comment by or-else** [comment]
I cannot reproduce. Try doing it on a fresh DB and a fresh installation. If it's still happening, tell me your API version and server-side details (rethink vs mysql etc).

**Comment by or-else** [comment]
Logcat would help too.

**Comment by or-else** [comment]
It has not been updated in a while. The bug was not reproducible and the code has changed substantially since it's been reported.
