### ISSUE TITLE
Vulnerable WebRTC Versions

### ISSUE THREAD

**Issue by dewebdes** [tinode/tindroid#140]
Hi, The problem was about google-play-developer-console to publish tindroid custom app on google play...
It said that the webrtc libs have the security issue:

![Capture](https://user-images.githubusercontent.com/40831732/208305268-b04afc00-8a64-4890-8e10-ff32ae6e4449.PNG)

I dont change the WebRTC dependencies , they are exists on lib directory: 

- google-webrtc-1.0.32006.aar
- google-webrtc-1.0.32006.pom

So, whats is your offer? please :|

**Comment by or-else** [comment]
Google stopped producing WebRTC builds for Android. If you know a newer version of webrtc aar, please give me a pointer. Otherwise we have to build it ourselves and that's a lot of work.

**Comment by or-else** [comment]
The latest version of webrtc is in `next`:
https://github.com/tinode/tindroid/commit/39af9522ba6b393a58256611837a242a50bc032e

**Comment by or-else** [comment]
Version 22 with updated WebRTC rolled out to production.
