### ISSUE TITLE
Messages received by large delay, sometimes!

### ISSUE THREAD

**Issue by dewebdes** [tinode/tindroid#145]
Sometimes it happens that messages send successfully but in receiver device it not immediately show.
Sometime this process will complete after some hours or one day.

My application have about 200 user and I feel that this behaviour go more and more by the application traffics grow.
I did not change anything about messaging engine on Tindroid/Tinode Server.

So what do u think about this problem?

**Comment by or-else** [comment]
The most likely reason is Google's FCM which delays push notifications. If this is something else then you need to provide more information.

**Comment by dewebdes** [comment]
No, This is not about push notifications...
I was disabled push notifications on server and application
and remove FCM codes from Android project

For notification purpose I was used a background service that connect to my server... and that's worked grate with no delay ... but when users see my notifications and enter the app then their messages board not updating yet (sometimes)

In my country the FCM was blocked most of times, and I can not use that for notification management.

**Comment by or-else** [comment]
> then their messages board not updating yet (sometimes)

Please show the logs.

**Comment by or-else** [comment]
Any update on this?
