### ISSUE TITLE
Query in the Application.

### ISSUE THREAD

**Issue by Nishantc10** [tinode/tindroid#15]
Hello Sir,
When the message arrives in android app, which method gets hit first?

**Comment by or-else** [comment]
This one: https://github.com/tinode/tindroid/blob/master/tinodesdk/src/main/java/co/tinode/tinodesdk/Connection.java#L200

**Comment by Nishantc10** [comment]
I want to make changes on incoming message,where should i do it?

**Comment by or-else** [comment]
I don't know. What do you want to change? Tell me more.

**Comment by or-else** [comment]
If you want to do something with the already parsed message, then look here:
https://github.com/tinode/tindroid/blob/master/tinodesdk/src/main/java/co/tinode/tinodesdk/Tinode.java#L393

**Comment by or-else** [comment]
There was no update in a week. I assume this is either resolved or no longer relevant. Closing.
