### ISSUE TITLE
Repetition of the message draft by disconnecting and connecting

### ISSUE THREAD

**Issue by Mj-binary** [tinode/tindroid#155]
When you write a message on the chat page and do not send it, if you go to another program and return to the chat page again, your message will be repeated twice. Also, this happens if you are on the chat page but the internet is disconnected and reconnected.

**To Reproduce**
1. Go to the chat page with Alice in Tindroid.
2. Type a few words but do not send it, for example "Hello "
3. Put Tindroid running in background and go to another app on your phone (or stay on Tindroid and disconnect from the internet)
4. back to Tindroid (or connect to internet)
5. Now the word you typed in the message field will be repeated, for example "HelloHello"

**Expected behavior**
The draft message remains unchanged.

Tindroid 
 - Version 0.22.8 (1665)
 - Device Xiaomi 11t
 - Android 13

**Server**
- sandbox.tinode.co

**Comment by or-else** [comment]
Already fixed in https://github.com/tinode/tindroid/commit/92f352565ae03d59a3538c61bef0c842108b709d
