### ISSUE TITLE
Error when installing apk

### ISSUE THREAD

**Issue by Tofdu31** [tinode/tindroid#16]
Hi,

I'im french, Sorry for my english...

I tried to install version 0.15.6 and version 0.15.5 on my smartphone.

I still have the same error message: `The package seems corrupted`

My smartphone is running Android 7.0

Thanks for your reponse

Best regards.

**Comment by or-else** [comment]
This is a debug APK. You may need to switch your phone to developer mode.

https://developer.android.com/studio/debug/dev-options

**Comment by or-else** [comment]
USB debugging must be enabled

**Comment by Tofdu31** [comment]
OK thanks
