### ISSUE TITLE
[Q] Thank u for make this open source . I have a question about this project build by AndroidStudio

### ISSUE THREAD

**Issue by fromtheredTH** [tinode/tindroid#162]
Hi. i want to set this project my computer.
I have problem to build apk this project .

flow
1. setting build.gradle
2. google-services.json under app folder
3. next i try build project

**but i have problem following errors.**

`: error: cannot find symbol
import co.tinode.tindroid.R;
                         ^
  symbol:   class R
  location: package co.tinode.tindroid
`
i try many things to fix it.

1.sync project with gradle files
2. clean & rebuild
3. invalidate cachces
4. reboot computer

my android studio 
version is 2024.1.1 and my gradle version is 8.6   & jbr version is 17.0.10

Thank you for read.

![R](https://github.com/tinode/tindroid/assets/135787869/e4ce69bf-e671-4b2c-8186-1be22cb38651)

![errorScreen](https://github.com/tinode/tindroid/assets/135787869/5c23160c-39d9-4b88-86d4-66a0fb3f44c6)

**Comment by or-else** [comment]
Please use forum for questions.

**Comment by fromtheredTH** [comment]
solve it . namespace issue

**Comment by fromtheredTH** [comment]
> Please use forum for questions.

okey. next time i use forum. thanks
