### ISSUE TITLE
Query in the Appliction...

### ISSUE THREAD

**Issue by Nishantc10** [tinode/tindroid#17]
In android application i want to add my own json format....so where should i add?
{"Domain_Name": "None"
"Domain_Value": "None"
"Original_Message": "hii"
"PopUp_Type": "flight"
"Response_Message": "flight"
"Ruled_Message": message
"UserType": "user"
"Username":"User name"}

And I want access individual object from my json,help me with that too...

**Comment by or-else** [comment]
> In android application i want to add my own json format....so where should i add?

I don't think I can answer your question unless you explain a bit more. What are you trying to achieve?

> And I want access individual object from my json,help me with that too...

If you want to parse json into a java object android then you can use a number of tools:

https://stackoverflow.com/questions/2591098/how-to-parse-json-in-java

Tindroid uses [Jackson](https://github.com/FasterXML/jackson-core) for that.

**Comment by or-else** [comment]
Put it into `content` field, i.e. something like
```json
{
  "data": {
    "topic":"usrt7yWQqDk3UM",
    "from":"usrt7yWQqDk3UM",
    "ts":"2018-10-24T09:25:09.775Z",
    "seq":13,
    "content":{
      "Domain_Name": "None",
      "Domain_Value": "None",
      "Original_Message": "hii",
      "PopUp_Type": "flight",
      "Response_Message": "flight",
      "Ruled_Message": message,
      "UserType": "user",
      "Username":"User name",
    }
  }
}
```
Keep in mind that the official clients will not be able to recognise and render your messages.

**Comment by Nishantc10** [comment]
{"data":{"topic":"usrlQLgvpIp7_g","from":"usrlQLgvpIp7_g","ts":"2018-10-24T07:21:54.931Z","seq":78,"content":" "}}

where i can get this?

**Comment by or-else** [comment]
I don't understand your question. Have you read the API docs?

**Comment by Nishantc10** [comment]
what I really want to achieve is, I want to send my json to bot but just want to display value of json object "original_message" from my json in app. Bot will also send me the response in same json format, I just want to display the value of json object "Response_Message" in app.

**Comment by or-else** [comment]
Send something like this:

```json
{
  "pub": {
    "id":"82148"
    "topic":"usrt7yWQqDk3UM",
    "head": {
      "x-your-app-name-Domain_Name": "None",
      "x-your-app-name-Domain_Value": "None",
      "x-your-app-name-PopUp_Type": "flight",
      "x-your-app-name-Response_Message": "flight",
      "x-your-app-name-Ruled_Message": message,
      "x-your-app-name-UserType": "user",
      "x-your-app-name-Username":"User name",
    },
    "content":"hii"
  }
}
```
In general it seems to me you are overcomplicating things.

**Comment by Nishantc10** [comment]
{
  "data": {
    "topic":"usrt7yWQqDk3UM",
    "from":"usrt7yWQqDk3UM",
    "ts":"2018-10-24T09:25:09.775Z",
    "seq":13,
    "content":{
      "Domain_Name": "None",
      "Domain_Value": "None",
      "Original_Message": "hii",
      "PopUp_Type": "flight",
      "Response_Message": "flight",
      "Ruled_Message": message,
      "UserType": "user",
      "Username":"User name",
    }
  }
}
i mgetting byte value in content instead of string, why?

**Comment by or-else** [comment]
This looks like Python code, so I assume you are using python:
```
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> resp = json.loads('{"Domain_Name":"None","Domain_Value":"None","Original_Message":"kpi","PopUp_Type":"flight","Response_Message":"kpi","Ruled_Message":"kpi","UserType":"User","Username":"Yash Parikh"}')
>>> resp['Username']
u'Yash Parikh'
>>> 
```
Everything works as expected. I guess your problem is with Pythons bytes vs string. It's not Tinode-specific.

**Comment by or-else** [comment]
Keep in mind that msg.data.content is bytes. Convert them to string.

**Comment by or-else** [comment]
Something as simple as
```
resp = msg.data.content.decode("utf8")
resp = json.dumps(resp)
```
should work.

**Comment by Nishantc10** [comment]
i want to add dynamic buttons with messege coming from bot, can you help me?

**Comment by or-else** [comment]
Do I understand correctly that you want forms like this:

<img width="274" alt="screenshot 2018-10-29 at 16 56 34" src="https://user-images.githubusercontent.com/5938143/47654388-c0735d80-db9b-11e8-8599-c503e52809fa.png">

**Comment by Nishantc10** [comment]
yes!

**Comment by or-else** [comment]
This is not possible just yet. I'll put it on the roadmap. Come back in ~2 weeks.

**Comment by Nishantc10** [comment]
ok thanks!

**Comment by Nishantc10** [comment]
in android application, where does the message gets set on chat bubble?

**Comment by or-else** [comment]
The feature is now available in https://github.com/tinode/chat/tree/devel and https://github.com/tinode/webapp/tree/devel. Android is next.

**Comment by Nishantc10** [comment]
actually i tried something but i m getting problem, when msg gets sent onBindViewHolder getting called multiple times and its creating buttons multiple times...

**Comment by or-else** [comment]
Android does not work yet. Only just was implemented so far

**Comment by Nishantc10** [comment]
when i opens chat it show the chat box in the way i want it but when i sends new msg it adds multiple buttons in all msgs.
eg. ss1 is the format i want  and ss2 is what i m getting...

![ss2](https://user-images.githubusercontent.com/43289057/48299914-0ca69200-e4fa-11e8-8fdd-4387016374ec.png)
![ss1](https://user-images.githubusercontent.com/43289057/48299915-0d3f2880-e4fa-11e8-8dad-0fb6344cbbbd.png)

**this is the code i have changed**

   public void onBindViewHolder(@NonNull final ViewHolder holder, int position) {

        ComTopic<VxCard> topic = (ComTopic<VxCard>) Cache.getTinode().getTopic(mTopicName);
        final StoredMessage m = getMessage(position);
        String rowID="11"+"0"+m.seq;

//        holder.layout.removeView(holder.itemView.findViewById(Integer.parseInt(rowID)));
            Log.i("Message:", m.content.toString());
        Log.i("Seq:", m.seq+"");
            Log.i("TopicName", mTopicName);
            Log.i("PositionTag", position + "");

            /*try {
                JSONObject obj = new JSONObject(String.valueOf(m.content));
                obj.toString();
                //Toast.makeText(mActivity, "" + obj, Toast.LENGTH_SHORT).show();
            } catch (JSONException e) {
                e.printStackTrace();
            }*/
            try {
                String popUp_type = null;
                String response_message = null;
                JSONArray popup_value = null;
                String value = null;
                String value2 = null;
                LinearLayout row = null;


                JSONObject obj = (new JSONObject(String.valueOf(m.content)));
                Log.d("jsons: ", obj + "");
                response_message = obj.getString("Response_Message");
                popUp_type = obj.getString("PopUp_Type");
                try {
                        popup_value = obj.getJSONArray("PopUp_Value");
                    if(popup_value.equals("None")) {
                        m.content = Drafty.parse(response_message);
                    }
                }catch (Exception e){
                    e.printStackTrace();
                }
//            Array popupvalue[] = (new Array[]{popup_value});

                if (popup_value != null && !popup_value.equals("None")) {
                    try{
                        holder.layout.removeView(row);
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                    row = new LinearLayout(mContext);
                    row.setId(Integer.parseInt(rowID));
                    row.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT));
                    row.setOrientation(LinearLayout.HORIZONTAL);
//                    row.setId();
                    for (int i = 0; i < popup_value.length(); i++) {
                        Log.i("popup_value_len: ", popup_value.length() + "; i= "+i);
                        if (popUp_type.equals("Integrated_Button")) {
                            try {
                                JSONArray arralist1 = new JSONArray(popup_value.getString(i));
                Log.i("onBindViewHoldergyju: ", popup_value.getString(0).toString().split(",")[0]);
//                          Button btnTag = new Button(mContext);
                                String ButtonID="12"+m.seq+"0"+i;
                                Button btnTag = new Button(mContext);
                                btnTag.setId(Integer.parseInt(ButtonID));
                                value = arralist1.getString(0);
                                value2 = arralist1.getString(1);
                                Log.i("onBindViewHoldergyjub: ", value);
                                Log.i("onBindViewHoldergyju3:", value2);
                                btnTag.setText(value);
                                row.addView(btnTag);

                                Log.i("ALLID: ", "Layout: "+row.getId()+"; Position: "+position+"; ButtonID: "+btnTag.getId()+"; I Val:"+i);
                                Log.i("ButtonID: ", btnTag.getId()+" "+position);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
//                if (popUp_type.equals("flight")) {
//                    try {
//
//                        JSONArray arralist1 = new JSONArray(popup_value.getString(i));
//                        Log.d("onBindViewHoldergyju: ", popup_value.getString(0).toString().split(",")[0]);
//                        Button btnTag = new Button(mContext);
//                        //                arralist.add(popup_value.getString(i));
//                        for (int j = 0; j <= arralist1.length(); j++) {
//                            LinearLayout row = new LinearLayout(mContext);
//                            row.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT));
//                            row.setOrientation(LinearLayout.HORIZONTAL);
//                            String value = arralist1.getString(0);
//                            String value2 = arralist1.getString(1);
//                            Log.d("onBindViewHoldergyjub: ", value);
//                            Log.d("onBindViewHoldergyju3:", value2);
//                            String id = arralist1.getString(1);
//                            Log.d("onBindViewHoldergyjuA: ", id);
//                            row.removeView(btnTag);
//                            for (int k = 1; k < value.length(); k++) {
//                                btnTag = new Button(mContext);
//
//                                btnTag.setText(value);
////                                btnTag.setTag(value2);
//                                row.addView(btnTag);
//                            }
//                            holder.layout.addView(row);
//                            m.content = Drafty.parse(response_message);
//                        }
//                    }catch (Exception e){
//                        e.printStackTrace();
//                    }
//                }
                    }
                    m.content = Drafty.parse(response_message);
                    holder.layout.addView(row);
                } else {
                    m.content = Drafty.parse(response_message);
                }
//            Log.d("onBindViewHolderid: ",arralist.get(0));
                //String var = obj.getString("");
//            Log.d( "onBindViewHolder1234: ",response_message);
//            Log.d( "onBindViewHolder12: ",popUp_type);
//            Log.d( "onBindViewHolder123: ",popup_value+"");
//            m.content=Drafty.parse(response_message);
//            try {
//                holder.b1.setVisibility(View.GONE);
//                if (popUp_type.equals("Integrated_Button")){
//                    if(holder.b1.getVisibility()== View.GONE) {
//                        holder.b1.setVisibility(View.VISIBLE);
//                        m.content = Drafty.parse(response_message);
//                        holder.b1.setOnClickListener(new View.OnClickListener() {
//                            @Override
//                            public void onClick(View v) {
//                                Toast.makeText(mContext, "button clicked", Toast.LENGTH_SHORT).show();
//                            }
//                        });
//                    }
//
//                } else if (popUp_type.equals("flight")) {
//                    if(holder.b1.getVisibility()== View.GONE) {
//                        holder.b1.setVisibility(View.VISIBLE);
//                        m.content = Drafty.parse(response_message);
//                        holder.b1.setOnClickListener(new View.OnClickListener() {
//                            @Override
//                            public void onClick(View v) {
//                                Toast.makeText(mContext, "button clicked", Toast.LENGTH_SHORT).show();
//                            }
//                        });
//                    }
//                } else {
//                    if(holder.b1.getVisibility()== View.VISIBLE) {
//                    holder.b1.setVisibility(View.GONE);
//                    m.content = Drafty.parse(response_message);
//                    }else {
////                        holder.b1.setVisibility(View.GONE);
//                        m.content = Drafty.parse(response_message);
//                    }
//                }
//            }catch (Exception e){
//                e.printStackTrace();
//                m.content = Drafty.parse(response_message);
//            }
//            Log.d( "mcontent: ",m.content+"");
                //Toast.makeText(mActivity, ""+response_message, Toast.LENGTH_SHORT).show();
            } catch (JSONException e) {
                e.printStackTrace();
//            m.content = Drafty.parse(response_message);

            }

**Comment by Nishantc10** [comment]
when i opens chat it show the chat box in the way i want it but when i sends new msg it adds multiple buttons in all msgs.
eg. ss1 is the format i want and ss2 is what i m getting...
![ss1](https://user-images.githubusercontent.com/43289057/48299954-cef63900-e4fa-11e8-8dd6-ff917ff0e903.png)
![ss2](https://user-images.githubusercontent.com/43289057/48299955-cef63900-e4fa-11e8-897a-27d06afc95ed.png)

**Comment by Nishantc10** [comment]
**the code i added is:**
   public void onBindViewHolder(@NonNull final ViewHolder holder, int position) {

        ComTopic<VxCard> topic = (ComTopic<VxCard>) Cache.getTinode().getTopic(mTopicName);
        final StoredMessage m = getMessage(position);
        String rowID="11"+"0"+m.seq;

            Log.i("Message:", m.content.toString());
			Log.i("Seq:", m.seq+"");
            Log.i("TopicName", mTopicName);
            Log.i("PositionTag", position + "");

            try {
                String popUp_type = null;
                String response_message = null;
                JSONArray popup_value = null;
                String value = null;
                String value2 = null;
                LinearLayout row = null;


                JSONObject obj = (new JSONObject(String.valueOf(m.content)));
                Log.d("jsons: ", obj + "");
                response_message = obj.getString("Response_Message");
                popUp_type = obj.getString("PopUp_Type");
                try {
                        popup_value = obj.getJSONArray("PopUp_Value");
                    if(popup_value.equals("None")) {
                        m.content = Drafty.parse(response_message);
                    }
                }catch (Exception e){
                    e.printStackTrace();
                }
                if (popup_value != null && !popup_value.equals("None")) {
                    try{
                        holder.layout.removeView(row);
                    }catch (Exception e){
                        e.printStackTrace();
                    }
                    row = new LinearLayout(mContext);
                    row.setId(Integer.parseInt(rowID));
                    row.setLayoutParams(new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT, LinearLayout.LayoutParams.WRAP_CONTENT));
                    row.setOrientation(LinearLayout.HORIZONTAL);
                    for (int i = 0; i < popup_value.length(); i++) {
                        Log.i("popup_value_len: ", popup_value.length() + "; i= "+i);
                        if (popUp_type.equals("Integrated_Button")) {
                            try {
                                JSONArray arralist1 = new JSONArray(popup_value.getString(i));
                Log.i("onBindViewHoldergyju: ", popup_value.getString(0).toString().split(",")[0]);
                                String ButtonID="12"+m.seq+"0"+i;
                                Button btnTag = new Button(mContext);
                                btnTag.setId(Integer.parseInt(ButtonID));
                                value = arralist1.getString(0);
                                value2 = arralist1.getString(1);
                                Log.i("onBindViewHoldergyjub: ", value);
                                Log.i("onBindViewHoldergyju3:", value2);
                                btnTag.setText(value);
                                row.addView(btnTag);

                                Log.i("ALLID: ", "Layout: "+row.getId()+"; Position: "+position+"; ButtonID: "+btnTag.getId()+"; I Val:"+i);
                                Log.i("ButtonID: ", btnTag.getId()+" "+position);
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                        }
                    }
                    m.content = Drafty.parse(response_message);
                    holder.layout.addView(row);
                } else {
                    m.content = Drafty.parse(response_message);
                }
            } catch (JSONException e) {
                e.printStackTrace();
            }
        // Disable attachment clicker.
        boolean disableEnt = (m.status == BaseDb.STATUS_QUEUED || m.status == BaseDb.STATUS_DRAFT) &&
                (m.content.getEntReferences() != null);

        mSpanFormatterClicker.setPosition(position);
        holder.mText.setText(SpanFormatter.toSpanned(mActivity, m.content, holder.mText.getMaxWidth(),
                disableEnt ? null : mSpanFormatterClicker));

**Comment by or-else** [comment]
Once again: Android is not done yet. Only webapp work. I'm working on it. It's work in progress.

**Comment by Nishantc10** [comment]
but you saw what i tried?

**Comment by or-else** [comment]
This seems to be a completely different code than Tinode. I'm sorry. I cannot help you debug your code. Maybe you can ask for help with debugging at stackoverflow.com

**Comment by Nishantc10** [comment]
on sending one msg, onBindViewHolder gets called multiple times?

**Comment by or-else** [comment]
onBindViewHolder is called once for every update of a view. It maybe called multiple time for every message. Here is the documentation for it:

https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter

**Comment by Nishantc10** [comment]
if i want to make changes in incoming bot replies,where should i do it?

**Comment by or-else** [comment]
Please explain in details what you want to change and why.

**Comment by Nishantc10** [comment]
Are you done with the dynamic buttons in android app?

**Comment by or-else** [comment]
Yes. https://github.com/tinode/tindroid/releases/tag/v0.15.9-rc2

**Comment by Nishantc10** [comment]
now please tell me where to change for dynamic buttons?

**Comment by or-else** [comment]
I don't understand the question. Please be more specific.

General message formatting, including forms, is here:
https://github.com/tinode/tindroid/blob/devel/app/src/main/java/co/tinode/tindroid/media/SpanFormatter.java
https://github.com/tinode/tindroid/blob/master/tinodesdk/src/main/java/co/tinode/tinodesdk/model/Drafty.java

**Comment by Nishantc10** [comment]
will you able to tell me, i want to put 'if' conditions on incoming messages,like i want to check whether msg is coming from user or from bot and add dynamic buttons and forms to it, where can i do it?

**Comment by Nishantc10** [comment]
From where i can add buttons to the message?

**Comment by or-else** [comment]
Send it from your chatbot. Format the message to have buttons like in these examples:
https://github.com/tinode/chat/blob/devel/tinode-db/data.json#L319
Then send it from the chatbot as `text/x-drafty`.

**Comment by or-else** [comment]
You should not add buttons to messages in the client. It's not a good architectural decision.

**Comment by Nishantc10** [comment]
from where i should change the color of left chat bubble?

**Comment by or-else** [comment]
https://github.com/tinode/tindroid/blob/devel/app/src/main/java/co/tinode/tindroid/UiUtils.java#L108

**Comment by Nishantc10** [comment]
If i want to call method of MessagesFragment's **"boolean sendMessage(Drafty content) {}"** from my newly created activity, how can i?

**Comment by or-else** [comment]
You generally cannot call a method from another activity because that activity may not exist. You have to implement that method in your activity too.
