### ISSUE TITLE
push Notification config on Android client and  Server side with linode.conf 

### ISSUE THREAD

**Issue by VirgileDjimgou** [tinode/tindroid#19]
hello linode community , how to configure the notifications on server side ? , i have already genrate my own google service.json file on firebase , but i don't know exactlly where i should paste the Cloud messaging api_key ....
do you have a tutorial how to configure this with the tinode.conf?

[*] Bug report

Server-side
  api.tinode.co
  Your own setup:
linux Ubuntu 16.04
version of tinode server, : v0.15.8-rc1'
database backend : mysql

Client-side
  Tindroid: Android app
Android API level ( 25 , 27).

**Comment by or-else** [comment]
Please do not create multiple identical issues. Use the first one you created:
https://github.com/tinode/chat/issues/175
