### ISSUE TITLE
Modify setting serveur

### ISSUE THREAD

**Issue by Tofdu31** [tinode/tindroid#20]
Hi,

I can not find the solution to remove the default IP address and put the one I need instead.

I found the 2 places where it was written 10.0.2.2:6060 as well as the name Host name but once the modifications made, I always have the same value to the IP address

![bug_ip](https://user-images.githubusercontent.com/22862175/48219332-8456ae80-e38c-11e8-89f7-17574b952e21.png)

**Comment by or-else** [comment]
Here:
https://github.com/tinode/tindroid/blob/master/app/src/main/res/values/strings.xml#L39

**Comment by or-else** [comment]
In general, you can always use GiHub search. It works well:
https://github.com/tinode/tindroid/search?q=10.0.2.2%3A6060&unscoped_q=10.0.2.2%3A6060

**Comment by Tofdu31** [comment]
I modified the strings.xml file :

```
    <string name="settings_host_name">Serveur Test</string>
    <string name="settings_use_tls">Use TLS</string>
    <string name="settings_wire_transport">Wire transport</string>
    <string name="settings_host_name_summary">Change server address</string>
    <string name="settings_use_tls_summary">Use secure connection</string>
    <string name="settings_wire_transport_summary">Select wire transport</string>
    <string name="default_host_name">192.168.100.1:6060</string>
```

I have however modified in the file strings.xml and moreover one finds the information in the cache.java:

```
    // public static String sHost = "api.tinode.co"; // remote host
    public static final String HOST_NAME = "192.168.1.100:6060"; // local host
```

**Comment by Tofdu31** [comment]
sorry, by creating a new virtual smartphone, I have the right address.

So I have a concern for cache. How do I clear the cache of a virtual smartphone?

**Comment by or-else** [comment]
Just change it.

**Comment by Tofdu31** [comment]
For information changes on for example replace "Host name" by server are well taken into account but not the IP address

For the IP address to be taken into account, I am forced to delete the virtual smartphone and recreate it.

thank you for your help
