### ISSUE TITLE
Android version compatibility?

### ISSUE THREAD

**Issue by pwFoo** [tinode/tindroid#24]
With which version is Tindroid backward compatible? 
A friend tried to install tindroid on Android 6 and installation fails. 

With Android 6 and web client push notifications doesn't work. But I don't know which Android versions support push notifications.

I just use the web client with desktop and mobile (Android 8) and it's work fine.

**Comment by or-else** [comment]
The minimum API version is 19 which is Android 4.4. Installation should not fail on Android 6.

**Comment by or-else** [comment]
API 23 is Android 6.0: https://source.android.com/setup/start/build-numbers

**Comment by or-else** [comment]
I just tested installation in an emulator API 23 and it was fine.

BTW, did he try to install the APK on a real phone? It's not possible unless the phone is in developers mode: https://developer.android.com/studio/debug/dev-options

**Comment by pwFoo** [comment]
Looks like something strange with the phone... 
no push notifications with browser version (chrome for android) and android app can't be installed...
Works fine (web version) with my own phone.

**Comment by or-else** [comment]
Does it have Google Services enabled? Check if it has playstore installed.

**Comment by pwFoo** [comment]
Should be... I ask my friend. Thanks!
