### ISSUE TITLE
How to just delete a conversation but not delete a topic?

### ISSUE THREAD

**Issue by shenshihao520** [tinode/tindroid#25]
I found a delete button (ChatListFragment)   but It doesn't work, the code like that:

 /**
     * This menu is shown when one or more items are selected from the list
     */
    @Override
    public boolean onActionItemClicked(ActionMode mode, MenuItem item) {
        switch (item.getItemId()) {
            case R.id.action_delete:
                SparseBooleanArray selected = mAdapter.getSelectedIds();
                for (int i = 0; i < selected.size(); i++) {
                    if (selected.valueAt(i)) {
                        Log.d(TAG, "deleting item at " + selected.keyAt(i));
                    }
                }
                // Close CAB
                mode.finish();
                return true;

            case R.id.action_mute:
                Log.d(TAG, "muting item");
                mode.finish();
                return true;

            case R.id.action_edit:
                Log.d(TAG, "editing item");
                mode.finish();
                return true;

            default:
                Log.d(TAG, "unknown menu action");
                return false;
        }
    }

How to just delete a conversation but not delete a topic? or can you tell me how to make a contract list.
thanks!    My English is so bad , forgive me.

**Comment by or-else** [comment]
Yes, it has not been finished yet. I'll add it in the next release.

**Comment by or-else** [comment]
This has been fixed for a while. Are there any remaining issues?
