### ISSUE TITLE
Query in the Tindroid Application

### ISSUE THREAD

**Issue by Nishantc10** [tinode/tindroid#28]
How to change the color of the right bubble?

**Comment by or-else** [comment]
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/UiUtils.java#L107

**Comment by Nishantc10** [comment]
From where we should change the color?

**Comment by or-else** [comment]
The color is assigned here:
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/MessagesListAdapter.java#L345

So, you need to assign `bgColor` in these two cases:
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/MessagesListAdapter.java#L326
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/MessagesListAdapter.java#L337

**Comment by or-else** [comment]
BTW, I'll move the colors to the resource in the next release.

**Comment by Nishantc10** [comment]
Thank You.
