### ISSUE TITLE
Not focusing to conversation fragment from push notification.

### ISSUE THREAD

**Issue by trademkose** [tinode/tindroid#29]
Hi,
Android app doesn't focus to related fragment of conversation when I click to New Message Push notification.

Best regards.

**Comment by or-else** [comment]
I cannot reproduce. Please provide more information.

I just fixed an issue when the notification was missing altogether: https://github.com/tinode/tindroid/commit/40aeb2c7be7a0d8fc622fab12af684a9934c29d8. But that seems to be different from the issue you described.

**Comment by or-else** [comment]
Any update on this?

**Comment by or-else** [comment]
With help of @maksfreetimer I found a bug which may have caused this issue. It's been fixed on the server side.

**Comment by or-else** [comment]
A possible fix has been released in https://github.com/tinode/chat/releases/tag/v0.15.13-rc2
If the problem remains, please open another issue and provide more details. Thanks.
