### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Nishantc10** [tinode/tindroid#30]
cannot resolve symbol error for(android.support.v7.app.AppCompatActivity ) in new update, why? can u please explain.

**Comment by or-else** [comment]
I just did a quick check. There are no dependencies on `android.support.v7.app.AppCompatActivity` anywhere in the code. Only `androidx.appcompat.app.AppCompatActivity`.
Something must be wrong with your Android Studio setup or your version of the app is out of sync. Try upgrading the Studio to the latest stable version (3.3.1), then use the menu `File -> Invalidate caches/Restart...`

**Comment by Nishantc10** [comment]
but it worked fine with last update

**Comment by or-else** [comment]
Well, it still works fine here.

**Comment by Nishantc10** [comment]
i have added android.support.v7.app.AppCompatActivity dependancy in app still its giving error but older app is working fine

**Comment by or-else** [comment]
You should not do that. The main branch has been switched to androidx while your code still references support libraries. Find all support library dependencies in your code and replace them with androidx equivalents.

**Comment by or-else** [comment]
You should not do that. The main branch has been switched to androidx while your code still references support libraries. Find all support library dependencies in your code and replace them with androidx equivalents.

**Comment by or-else** [comment]
Any update on this?
