### ISSUE TITLE
Search users based on their discovery tags

### ISSUE THREAD

**Issue by mohgh** [tinode/tindroid#32]
There is a feature in WebApp that we are able to find topics based on their public tags and subscribe to them (This option is very useful in finding open to subscribing topics and is existed in Telegram for example). Is there a similar feature in Tindroid? I know there's already an issue similar to this (#3) but I couldn't understand how using "Start by Id" option is related to this.

**Comment by or-else** [comment]
Yes, this functionality is missing in Tindroid (present only in the webapp). It is in the plans to build next.

**Comment by or-else** [comment]
In progress at https://github.com/tinode/tindroid/tree/find
