### ISSUE TITLE
Outstanding promises not rejected on disconnect

### ISSUE THREAD

**Issue by aforge** [tinode/tindroid#35]
In Tinode.handleDisconnect:
https://github.com/tinode/tindroid/blob/master/tinodesdk/src/main/java/co/tinode/tinodesdk/Tinode.java#L449-L454
reject all outstanding promises.
But by the time it's called, the mFutures map is already empty due to
https://github.com/tinode/tindroid/blob/master/tinodesdk/src/main/java/co/tinode/tinodesdk/Tinode.java#L434

**Comment by or-else** [comment]
Fixed

**Comment by or-else** [comment]
Released in 0.15.15-rc1
