### ISSUE TITLE
[Android] Group Chat 

### ISSUE THREAD

**Issue by wttbddsk** [tinode/tindroid#42]
While creating a new group chat with other user which is also online, group chat is to be seen only on **creator's** device whilst on **invited** device chat is invisible. The only way to see the group chat on invited device is to close and then re-open the app.

**Comment by or-else** [comment]
Could you please describe the exact steps to reproduce.

**Comment by or-else** [comment]
Seems like it either has been resolved or no longer relevant. Feel free to reopen.
