### ISSUE TITLE
File uploads stall when app restarts

### ISSUE THREAD

**Issue by aforge** [tinode/tindroid#43]
1. Send a large file as an attachment.
2. While the file is uploading, kill the app.
3. Restart the app - the message draft is still there with the progress bar and the cancel button. However, it's making no progress.

We should either cancel (and update the UI to display an error on the message) or restart the upload.

**Comment by aforge** [comment]
I suspect we'll need to persist the state of the upload in a local database (sqlite being the default option). We have the same problem with iOS - the operating system will not do any of that work for us.
Whatever we decide to do, I'd prefer to keep the solutions for Android and iOS in sync so let's chat before moving forward with implementing.

**Comment by or-else** [comment]
Yes, that's what I was thinking too. The easiest is to cancel the unfinished upload on app restart. Restarting the upload on app restart is harder and has to take into account the possibility of the uploading file being deleted in the interim. Resuming the interrupted upload requires support on the server side and I would rather not support it right now.

A nicer option would be to hand over the large upload to a background service which signals the app on progress and completion. It's not too hard on Android.

**Comment by aforge** [comment]
Okay, sounds good.
Cancel is the easiest indeed. Let's stick with it.
Let us also keep shifting uploads to a background service as a feature/TODO.
