### ISSUE TITLE
Question, trying to connect server in application.

### ISSUE THREAD

**Issue by s0-hail** [tinode/tindroid#45]
Hi!
I just installed Tindroid application (tindroid-arm64-v8a-debug.apk) and also installed server (
tinode-mysql.linux-amd64.tar.gz) at http://67.207.84.4:6060.
but when i set my server in application, it says that :"login failed: failed to connect to server after 3000ms"
I would appropriate if you can help.
Best Regards .

**Comment by or-else** [comment]
Go to login screen, select Settings (three dots in the upper right corner), take a screenshot, post it here.

Thanks.

**Comment by s0-hail** [comment]
it seems is my port setting issues, Thnx for replying.
