### ISSUE TITLE
Question: why generate an additional APK?

### ISSUE THREAD

**Issue by s0-hail** [tinode/tindroid#46]
Hi
i have a question about your build.gradle
why do you generate 4 type APK based on architecture, while your project doesn't use any machine dependent code like C lib?

**Comment by or-else** [comment]
Because someone asked for it and it was easy to do:
https://github.com/tinode/tindroid/issues/31

**Comment by s0-hail** [comment]
i see
why? is  it make a difference?  there is no native code.

**Comment by or-else** [comment]
I don't know. Someone wanted it. I made it. I don't see any harm in it.

**Comment by s0-hail** [comment]
:D OK tnx for response.
but in my personal view, it just like defining a variable that not used anywhere. it's not good.
Best Regards.

**Comment by Kuvonchbeky** [comment]
Hi! How can I handle all incoming messages in the background service? I need to receive messages in background Service.

**Comment by Kuvonchbeky** [comment]
is it possible?

**Comment by or-else** [comment]
Please do not use closed issues to ask unrelated questions. Use these methods to get support:
 https://github.com/tinode/chat#getting-support
Yes, it's possible.
