### ISSUE TITLE
Orphaned connections on restarting a cluster

### ISSUE THREAD

**Issue by aforge** [tinode/tindroid#51]
Tindroid opens up connections and drops them immediately when the cluster restarts.

1. Bring up a cluster (with a load balancing proxy).
2. Connect Tinode to it.
3. Take down all the servers.
4. Bring up servers in a rapid succession.

Observe several "{hi} - {ctrl 201}" pairs in the logs.

These connections should either not be opened or closed immediately upon whatever the error that causes these connections to stall.

**Comment by or-else** [comment]
This is probably not a tindroid issue. It's likely an issue with the server.

**Comment by or-else** [comment]
I think I know what's going on here. When the nodes start in cluster mode they have to connect to each other to form a cluster. Before that happens the cluster is partitioned. And while it partitioned it rejects the requests:
https://github.com/tinode/chat/blob/master/server/session.go#L343

**Comment by aforge** [comment]
The response to {hi} messages is 201, not 502. So it must be something else.
Besides, Tinodios and the Web app do not exhibit this behavior. That's why I made this issue in the Tindroid repo.

**Comment by or-else** [comment]
Ah, OK. I think it's really minor. When firebase push token changes Tindroid reports the new value to the server using {hi}. Server incorrectly replied to these updates with 201 instead of 200. It has nothing to do with the cluster, it works the same way with a standalone server too. I've made a fix to the server to report 200 instead of 201 in these cases.

Also, Tindroid reports the firebase token even if it has not changed. I'll look into it next.

**Comment by or-else** [comment]
I've made a small change in Tindroid to save token only if the sync was successful:
https://github.com/tinode/tindroid/commit/60f06ade98d7fc368e1201a57253e1dbd85ecbf1

Otherwise it works as expected.

**Comment by aforge** [comment]
Cool!
Here's a supposed fix for this problem: https://github.com/tinode/tindroid/pull/52

Long story short: reconnect loop in Tindroid creates a new TinodeWsClient on every iteration and attempts to open a connection. If it fails, the opened sockets do not disappear and wait for the server to become available. Once the latter does, all these sockets open their respective connections (thus, sending {hi} to the server).

**Comment by or-else** [comment]
Interesting! I thought it would be garbage collected. Apparently not. Great catch. Thanks!
