### ISSUE TITLE
ERROR: CreateProcess error=2, The system cannot find the file specified

### ISSUE THREAD

**Issue by supaplextor** [tinode/tindroid#57]
**Describe the bug**
Trying to import/build in Android Studio

ERROR: CreateProcess error=2, The system cannot find the file specified

git is not installed on this Windows 10 PC, however,

static def gitVersionCode() {
    def process = "git rev-list --count HEAD".execute()

![image](https://user-images.githubusercontent.com/4638774/67913518-8e982c80-fb4a-11e9-95b5-0994726288f5.png)

Would be nice if git is not required. Thanks!

**Comment by or-else** [comment]
> ERROR: CreateProcess error=2, The system cannot find the file specified

Change this line
https://github.com/tinode/tindroid/blob/e1cf657f0a26c56824f75cd198d66f0a53a2ae38/app/build.gradle#L14
to something like 
`    versionCode 123`

and this line 
https://github.com/tinode/tindroid/blob/e1cf657f0a26c56824f75cd198d66f0a53a2ae38/app/build.gradle#L15
to something like
`    versionName "1.0"`


> Would be nice if git is not required. Thanks!

You are welcome to contribute a change which would make git dependency optional.

**Comment by or-else** [comment]
I assume this is resolved. If not, feel free to comment further.
