### ISSUE TITLE
Image update in TopicInfo closes the fragment

### ISSUE THREAD

**Issue by aforge** [tinode/tindroid#60]
When editing details of a group topic as the topic owner, new image upload immediately closes the TopicInfo fragment. The image in the app (locally) does not get updated. On the server, though, it does. So reloading the app displays the updated image for the group topic.

1. Log in as alice.
2. Open "Travel, travel, travel" topic.
3. Tap on "i" icon in the title bar. This will bring forward the TopicInfo fragment.
4. Upload a new image.
5. The fragment disappears. Image is not updated.

**Expected behavior**
The fragment should not disappear. Image should get updated right away.

**Comment by or-else** [comment]
Fixed
