### ISSUE TITLE
new message touch time not sync with server

### ISSUE THREAD

**Issue by pcgpcgpcg** [tinode/tindroid#65]
in metopic at routepres when new message arrived,
call topic.setTouched(new Date());

but the new Date() may not sync with the time on server.So I think server should add touchtime in pres msg.

**Comment by or-else** [comment]
Server updates `touched` when the message is sent:
https://github.com/tinode/chat/blob/devel/server/topic.go#L306

Yes, there could be a small difference between server's and client's timestamps. I don't think it matters though.

**Comment by or-else** [comment]
I've recently fixed some bugs related to `touched`:
https://github.com/tinode/chat/commit/ca455d7272053b0c9c7504b6bbd4e436a180a005

**Comment by pcgpcgpcg** [comment]
For example 
The client receives two pres messages，group B updates touched to 15:05:05.356，and group A updates touched to 15:05:05.332，so group list view calls sort() func order by touched desc(client-side time).  When the user clicks to enter group B，the client receives data message and updates touched to server-side time15:05:05.312. then it returns to group list view, sort() func is called and the list order is changed without new message.

**Comment by or-else** [comment]
I don't understand this:

> then it returns to group list view, sort() func is called and the list order is changed without new message.

What do you mean by "without new message"?

**Comment by abitcyanine** [comment]
Soring the group list of receiving two pres messages:
Group B(touched 15:05:05.356 client-side time, seqID 15)
Group A(touched 15:05:05.332 client-side time, seqID 33)

The user enters group B and receives data message for seqID=15, then returns to list view.
Soring the group list:
Group A(touched 15:05:05.332 client-side time, seqID 33)  
Group B(touched 15:05:05.312 server-side time, seqID 15)
The client did not receive a new message, but the sorting changed

**Comment by abitcyanine** [comment]
The data message updates touched and affects the sorting

**Comment by or-else** [comment]
> The client did not receive a new message, but the sorting changed

Yes, it may happen. But that rather minor: it happens very infrequently and it's a small UI inconsistency. Fixing it would require adding a timestamp to `{pres}` messages.

We are currently working on fetching messages in background on push notification, just like Whatsapp. Once implemented this problem will be even less visible.

**Comment by abitcyanine** [comment]
Yes, when we test sorting frequently, this happens occasionally, so we find this problem and plan to add touched in Pres

**Comment by abitcyanine** [comment]
Looking forward to your future repair

**Comment by or-else** [comment]
I think is is pretty much a non-isse anymore. Do you still see this problem?
