### ISSUE TITLE
connecting Tindroid running on android device with network server

### ISSUE THREAD

**Issue by music24by7** [tinode/tindroid#76]
Hi,

I've setup tinode server on a local PC which is accessible with 127.0.0.1:6060 and also with 192.168.0.199:6060 from same local PC.

Now I tried tindroid on an emulator AVD phone by changing string.xml to  
<string name="emulator_host_name" translatable="false">192.168.0.199:6060</string>
This works fine.

Now I want to use this on real mobile device. Can you please provide what are the sequence of steps(how to replace sandbox.tinode.co with local IP)?

Thanks

**Comment by or-else** [comment]
Here: https://github.com/tinode/tindroid/blob/master/app/build.gradle#L37
