### ISSUE TITLE
Messages are duplicated

### ISSUE THREAD

**Issue by mohgh** [tinode/tindroid#86]
### Subject of the issue
Sometimes messages are duplicated, meaning several copies of the same message are present inside the chat. It happens with text and image messages. This issue has appeared before. Last time the problem was about sending the same message multiple times. I think this is the same issue because duplicated messages have different receive times and get downloaded again after clean re-installation of the app.

#### Server-side
- [ ] web.tinode.co, api.tinode.co
- [ ] sandbox.tinode.co
- [x] Your own setup:
  * platform: Linux
  * version of Tinode server: Latest
  * database backend: MySql
  * standalone

#### Client-side
- [ ] TinodeWeb/tinodejs: javascript client
  * Browser make and version.
- [x] Tindroid: Android app
  * Android API level (e.g. 25).
  * hardware, Samsung Galaxy S7Edge
- [ ] Tinodios: iOS app
  * iOS version
  * Simulator or hardware, if hardware describe it.
- [ ] tn-cli
  * Python version
- [ ] Chatbot
  * Python version
- Version of the client, e.g. `0.15.1`
- [ ] Your own client. Describe it:
  * Transport (gRPC, websocket, long polling)
  * Programming language.
  * gRPC version, if applicable.

**Comment by or-else** [comment]
What is the version of the app?

**Comment by or-else** [comment]
Can you show the logcat and the server-side log?

**Comment by mohgh** [comment]
I'm on the last commit of the devel branch.
Actually reproducing this bug is not easy and It happens occasionally so I can not send any useful logcat or server logs.

**Comment by or-else** [comment]
Please try to provide additional information. Otherwise it's unclear to me how to replicate the bug.

**Comment by or-else** [comment]
Is this resolved? Still relevant?
