### ISSUE TITLE
Gradle sync failed

### ISSUE THREAD

**Issue by mesibo-user** [tinode/tindroid#93]
15:29	Gradle sync started
15:30	Gradle sync failed: For input string: ""

whats wrong with this:

```
static def gitVersionCode() {
def process = "git rev-list --count HEAD".execute()
return process.text.toInteger()
}

```

**Comment by or-else** [comment]
You probably don't have git installed or configured for your project folder.

**Comment by mesibo-user** [comment]
I have
![git](https://user-images.githubusercontent.com/70767756/92720740-f3bcd100-f35c-11ea-909c-69c360e1300f.png)

**Comment by or-else** [comment]
Then git is probably not initialised in your project folder. What do you see when you run `git rev-list --count HEAD` from your project folder?
