### ISSUE TITLE
New messages badge in the conversations list does not update correctly

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/tindroid#96]
New messages count in the conversations list does not update correctly if there is more than 1 new message. 

For example, I see that I have 3 new messages from Dave. I access the conversation and then return to the conversations list. I still see that I have 2 new messages from Dave. I access the conversation one more time and only after that, when I return to the conversations list, the new messages badge disappears.

![badge](https://user-images.githubusercontent.com/54183931/93672205-f330e280-faa0-11ea-8b7d-174c178cc07e.png)

I see this problem persists in Tindroid that is available on Google Play, as well as on Github. I see the problem on 2 phones - Android 5.1.1 and Android 8.1.0

**Comment by or-else** [comment]
Such bug reports are not useful. Try debugging first, at least get the logs.

**Comment by sanmiguel2019** [comment]
OK, sorry, but I am not an Android developer. I was thinking that if I find a problem in Tindroid I can post it without debugging. Some problems may not be noticed by other people. There is also a problem with logging in with a different username after logout but if it's not welcome, I can stop posting.

**Comment by or-else** [comment]
Please fugure out a way to create helpful reports. Reports like the one above are not useful. I spent 20 minutes trying to reproduce it to no avail. At least list steps which reliably reproduce the problem on sandbox. List the app version. The bug report template was created for a reason.

**Comment by or-else** [comment]
I think I know what you think the problem is. The badge does not clear instantly. You need to spend 1.5-2 seconds in the chat before before the badge is cleared. It's by design.

**Comment by sanmiguel2019** [comment]
Well, looks that found the problem. When I installed Tinode on my server, I also created users for testing purposes using `data.json` file. And first of all the badge didn't clear correctly - I had to access each topic 2 times to clear the badge.

But now when I send/read new messages, the badge clears correctly.
