### ISSUE TITLE
Suggestion: notifications when user is in the topic

### ISSUE THREAD

**Issue by sanmiguel2019** [tinode/tindroid#97]
I suggest to make  changes to FBaseMessagingService.java file and to add this code:

```
    public boolean isScreenOn() {
        PowerManager powerManager = (PowerManager) getSystemService(POWER_SERVICE);
        boolean result= powerManager.isInteractive();
        return result;
    }
```

And to change the line:

`if (visibleTopic != null && visibleTopic.equals(topicName) ) {`

to:

```
boolean CheckScreenOn = isScreenOn();
if (visibleTopic != null && visibleTopic.equals(topicName) && CheckScreenOn) {
```

I m not an Android developer and probably it's possible to do it in another way but for me this fixes problem with notifications.

The problem appears when user reads a topic and turns phone's screen off without returning to the list of the topics. He stops getting notifications for this topic and I think it's not correct. There is no need to display notifications only when phone's screen is on. Otherwise, the user may not know that he has new messages.

**Comment by or-else** [comment]
The app detects going into the background and disconnects:
https://github.com/tinode/tindroid/blob/master/app/src/main/java/co/tinode/tindroid/TindroidApp.java#L148

Could you please show the steps to reproduce the problem.

**Comment by or-else** [comment]
The FBMessaging service does not disconnect and it's a bug, but that has nothing to do with going into the background. The service will disconnect in the next release.

**Comment by sanmiguel2019** [comment]
Comment in the following code: 

```
  if (visibleTopic != null && visibleTopic.equals(topicName)) {
                // No need to display a notification if we are in the topic already.
                Log.d(TAG, "Topic is visible, no need to show a notification");
                return;
            }

```
in the `FBaseMessagingService.java `file says:

**No need to display a notification if we are in the topic already.**

and it works. Unfortunately it works even with phone's screen off.

For example, I get a new message from Alice. I tap on the notification, access the topic, write answer, send it to Alice and turn phone's screen off, leaving the topic open. I don't get notifications for this topic anymore.

To get future notifications for this topic, I need to push "back" button after sending message to Alice, and return to the topics list.
I see this problem on 2 Android phone's. For a long time, I couldn't understand why notifications sometimes don't work. Then I checked `FBaseMessagingService.java `file, made changes that I published in my 1st post and the problem is gone.

**Comment by or-else** [comment]
The `visibleTopic` is set to `null` when `onWindowFocusChanged(false)` is called. Are you saying `onWindowFocusChanged` is not called when the screen is turned off? Let me check that.

**Comment by or-else** [comment]
This should fix the problem you have been observing:
https://github.com/tinode/tindroid/commit/bd8ce597f805ec3ad5f10d2b2d5dc6720af6fd43

Specifically this change:
https://github.com/tinode/tindroid/commit/bd8ce597f805ec3ad5f10d2b2d5dc6720af6fd43#diff-b195deb0e46573e2c9ada2d75e4bb18cR423

**Comment by sanmiguel2019** [comment]
Yes, now the problem is fixed. thanks.
